name: tests

on:
  pull_request:
  push:
    branches:
      - master
      - tidb

jobs:
  tidb:
    name: TiDB
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        version: [ v6.1.0, v5.4.1 ]

    steps:
      - uses: actions/checkout@v2

      - name: Install tiup
        run: curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh

      - name: Run tiup
        run: nohup /home/runner/.tiup/bin/tiup playground ${{ matrix.version }} > nohup.txt &
      
      - name: Wait TiDB ready
        run: sleep 5s && cat nohup.txt
        shell: bash
        
      - name: Vertify TiDB connection from host
        run: mysql -h 127.0.0.1 -P 4000 -u root -e "SELECT VERSION();"
