name: tests

on:
  pull_request:
  push:
    branches:
      - master
      - tidb

jobs:
  tidb:
    name: TiDB
    runs-on: ubuntu-20.04
    env:
      DATABASE_URL: "mysql://root:@127.0.0.1:4000"
    strategy:
      fail-fast: false
      matrix:
        version: [ v6.1.0, v5.4.1 ]
        example: [sqlx_tidb]

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install tiup
        run: curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh

      - name: Run tiup
        run: RUNNER_TRACKING_ID="" && (nohup /home/runner/.tiup/bin/tiup playground ${{ matrix.version }} > nohup.txt &)
      
      - name: Wait TiDB ready
        run: sleep 15s && cat nohup.txt
        shell: bash
        
      - name: Vertify TiDB connection from host
        run: mysql -h 127.0.0.1 -P 4000 -u root -e "SELECT VERSION();"
